---
apiVersion: v1
kind: Namespace
metadata:
  name: ruby-prometheus-metrics

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ruby-app-config
  namespace: ruby-prometheus-metrics
data:
  ELASTIC_APM_SERVER_URL: "https://your-apm-server-url:443"

---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-apm-secret
  namespace: ruby-prometheus-metrics
type: Opaque
data:
  ELASTIC_APM_SECRET_TOKEN: <base64-encoded-apm-token>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-app
  namespace: ruby-prometheus-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-app
  template:
    metadata:
      labels:
        app: ruby-app
    spec:
      containers:
      - name: ruby-app
        image: banjodocker/ruby-prometheus-app:latest
        ports:
        - containerPort: 4567
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        envFrom:
        - configMapRef:
            name: ruby-app-config
        - secretRef:
            name: elastic-apm-secret

---
apiVersion: v1
kind: Service
metadata:
  name: ruby-app-service
  namespace: ruby-prometheus-metrics
spec:
  selector:
    app: ruby-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4567

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ruby-prometheus-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ruby-prometheus-metrics
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruby-app-ingress
  namespace: ruby-prometheus-metrics
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ruby-app-service
            port: 
              number: 80
